name: release

# last day of the month at 21:00
on:
  push:
    branches:    
      - main
  schedule:
    - cron: '0 21 30 4,6,9,11        *'
    - cron: '0 21 31 1,3,5,7,8,10,12 *'
    - cron: '0 21 28 2               *'

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.0'
          - '7.1'
          # - '7.2'
          # - '7.3'
          # - '7.4'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      # -
      #   name: Run Docker Buildx
      #   run: |
      #     docker buildx build \
      #       --label SOURCE_CODE="github.com/mykiwi/phaudit" \
      #       --label GIT_SHA=${{ github.sha }} \
      #       --label GIT_REF=${{ github.ref }} \
      #       --pull \
      #       --tag mykiwi/phaudit:${{ matrix.php-version }} \
      #       --file php${{ matrix.php-version }}.Dockerfile \
      #       .

      -
        name: Prepare release date
        id: release-date
        run: |
          date=$(date +"%y.%m")
          echo "::set-output name=name::$date"

      -
        name: Prepare docker labels
        id: docker-labels
        run: |
          build-date=$(date --rfc-3339="seconds")
          labels="build-date=$build-date,version=${{ matrix.php-version }}-${{ steps.release-date.outputs.name }},vsc-url=https://github.com/mykiwi/phaudit,vsc-ref=${{ github.ref }},vsc-sha=${{ github.sha }}"
          echo "::set-output name=value::$labels"
    
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

          repository: mykiwi/phaudit-tmp
          tags: ${{ matrix.php-version }}, ${{ matrix.php-version }}-${{ steps.release-date.outputs.name }}

          build_args: PHP_VERSION=${{ matrix.php-version }}
          labels: ${{ steps.docker-labels.outputs.value }}
