name: release

# last day of the month at 21:00
on:
  push:
    branches:    
      - main
  schedule:
    - cron: '0 21 30 4,6,9,11        *'
    - cron: '0 21 31 1,3,5,7,8,10,12 *'
    - cron: '0 21 28 2               *'

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '70'
          - '71'
          # - '72'
          # - '73'
          # - '74'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build --tag=mykiwi/phaudit:${{ matrix.php-version }} --file=php${{ matrix.php-version }}.Dockerfile .
