name: release

# last day of the month at 21:00
on:
  push:
    branches:    
      - main
  schedule:
    - cron: '0 21 30 4,6,9,11        *'
    - cron: '0 21 31 1,3,5,7,8,10,12 *'
    - cron: '0 21 28 2               *'

matrix:
  php-versions:
    - '70'
    - '71'
    # - '72'
    # - '73'
    # - '74'

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build -t mykiwi/phaudit:${{ matrix.php-version }}
        with:
          php-version: ${{ matrix.php-versions }}
