name: release

# last day of the month at 21:00
on:
  push:
    branches:    
      - main
  schedule:
    - cron: '0 21 30 4,6,9,11        *'
    - cron: '0 21 31 1,3,5,7,8,10,12 *'
    - cron: '0 21 28 2               *'

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '7.0'
          - '7.1'
          # - '7.2'
          # - '7.3'
          # - '7.4'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      -
        name: Prepare release date
        id: release-date
        run: |
          date=$(date +"%y.%m")
          echo "::set-output name=name::$date"
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}-tmp
          tags: ${{ matrix.php-version }}, ${{ matrix.php-version }}-${{ steps.release-date.outputs.name }}
          build_args: PHP_VERSION=${{ matrix.php-version }}
          add_git_labels: true
      -
        name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: debug
        run: |
          docker images
      -
        name: Push images on GitHub
        run: |
          docker tag ${{ github.repository }}:${{ matrix.php-version }} docker.pkg.github.com/${{ github.repository }}:${{ matrix.php-version }}
          docker tag ${{ github.repository }}:${{ matrix.php-version }} docker.pkg.github.com/${{ github.repository }}:${{ matrix.php-version }}-${{ steps.release-date.outputs.name }}

          # docker -h push docker.pkg.github.com/${{ github.repository }}:${{ matrix.php-version }}
          # docker -h push docker.pkg.github.com/${{ github.repository }}:${{ matrix.php-version }}-${{ steps.release-date.outputs.name }}
